package com.app.ancoturf.domain.common

object UseCaseConstants {

    const val ORDERED_IMAGE_IDS = "ORDERED_IMAGE_IDS"
    const val FIRST_NAME = "FIRST_NAME"
    const val LAST_NAME = "LAST_NAME"
    const val PASSWORD = "PASSWORD"
    const val DEVICE_TOKEN = "DEVICE_TOKEN"
    const val OLD_PASSWORD = "OLD_PASSWORD"
    const val EMAIL = "EMAIL"
    const val BUSINESS_NAME = "BUSINESS_NAME"
    const val ABN = "ABN"
    const val PHONE_NUMBER = "PHONE_NUMBER"
    const val PROFILE_URL = "PROFILE_URL"
    const val USER_TYPE = "USER_TYPE"

    //product filter
    const val PRODUCT_CATEGORY_IDS = "PRODUCT_CATEGORY_IDS"
    const val PRODUCT_TAG_IDS = "PRODUCT_TAG_IDS"
    const val PRICE_MIN = "PRICE_MIN"
    const val PRICE_MAX = "PRICE_MAX"
    const val SEARCH = "SEARCH"
    const val SORT_BY = "SORT_BY"
    const val DELIVERY_DATE_FROM = "DELIVERY_DATE_FROM"

    const val PRODUCT_ID = "PRODUCT_ID"
    const val PRODUCT_SORT_NAME = "PRODUCT_SORT_NAME"
    const val PER_PAGE = "PER_PAGE"

    const val REVIEW_TEXT = "REVIEW_TEXT"
    const val RATING = "RATING"
    const val USER_ID = "USER_ID"
    const val NAME = "NAME"

    const val PORTFOLIO_ID = "PORTFOLIO_ID"
    const val PORTFOLIO_IMAGES = "PORTFOLIO_IMAGES"
    const val PROJECT_NAME = "PROJECT_NAME"
    const val CITY = "CITY"
    const val BUDGET = "BUDGET"
    const val PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION"
    const val ADDRESS = "ADDRESS"
    const val FEATURED_IMAGE_INDEX = "FEATURED_IMAGE_INDEX"
    const val DELETED_IMAGE_IDS = "DELETED_IMAGE_IDS"
    const val PRODUCTS = "PRODUCTS"
    const val CUSTOM_PRODUCTS = "CUSTOM_PRODUCTS"
    const val UPDATED_CUSTOM_PRODUCTS = "UPDATED_CUSTOM_PRODUCTS"
    const val DELETED_CUSTOM_PRODUCT_IDS = "DELETED_CUSTOM_PRODUCT_IDS"
    const val DELETED_PRODUCT_IDS = "DELETED_PRODUCT_IDS"
    const val FEATURED_IMAGE_ID = "featured_Image_Id"
    const val IMAGE_IDS = "IMAGE_IDS"

    const val QUOTE_ID = "QUOTE_ID"
    const val QUOTEID = "quoteID"
    const val CUSTOMER_ID = "CUSTOMER_ID"
    const val CUSTOMER_NAME = "CUSTOMER_NAME"
    const val CUSTOMER_ADDRESS = "CUSTOMER_ADDRESS"
    const val CUSTOMER_EMAIL = "CUSTOMER_EMAIL"
    const val CUSTOMER_MOBILE = "CUSTOMER_MOBILE"
    const val CUSTOMER_PHONE = "CUSTOMER_PHONE"
    const val DELIVERY_COST = "DELIVERY_COST"
    const val DELIVERY_DATE = "DELIVERY_DATE"
    const val MOBILE_NUMBER = "MOBILE_NUMBER"
    const val WEB_URL = "WEB_URL"
    const val CONTACT_NAME = "CONTACT_NAME"
    const val PAYMENT_TERMS = "PAYMENT_TERMS"
    const val DISCLAIMER = "DISCLAIMER"
    const val REGISTERED_FOR_GST = "REGISTERED_FOR_GST"
    const val LOGO_URL = "LOGO_URL"
    const val SEND_QUOTE_TO = "SEND_QUOTE_TO"
    const val DEEP_LINK_URL = "deeplink_url"
    const val NOTE = "note"

    const val CUSTOM_PRODUCT_ID = "CUSTOM_PRODUCT_ID"
    const val DESCRIPTIONS = "DESCRIPTIONS"
    const val PRICE = "PRICE"
    const val IMAGE = "IMAGE"

    //filter
    const val STATUS = "STATUS"
    const val ORDER_STATUS = "ORDER_STATUS"
    const val DELIVERY_STATUS = "DELIVERY_STATUS"
    const val COST_MIN = "COST_MIN"
    const val COST_MAX = "COST_MAX"
//    const val ADDRESS = "ADDRESS"
//    const val SORT_BY = "SORT_BY"

    //orderDetail
    const val REFERENCE_NO = "REFERENCE_NO"

    //product database
//    const val PRODUCT_ID = "PRODUCT_ID"
    const val PRODUCT_UPDATE = "PRODUCT_UPDATE"
    const val PRODUCT_NAME = "PRODUCT_NAME"
    const val PRODUCT_FEATURE_IMAGE_URL = "PRODUCT_FEATURE_IMAGE_URL"
    const val PRODUCT_QTY = "PRODUCT_QTY"
    const val PRODUCT_PRICE = "PRODUCT_PRICE"
    const val PRODUCT_CATEGORY_ID = "PRODUCT_CATEGORY_ID"
    const val PRODUCT_UNIT = "PRODUCT_UNIT"
    const val PRODUCT_UNIT_ID = "PRODUCT_UNIT_ID"
    const val PRODUCT_BASE_TOTAL_PRICE = "PRODUCT_BASE_TOTAL_PRICE"
    const val PRODUCT_IS_TURF = "PRODUCT_IS_TURF"
    const val PRODUCT_TOTAL_PRICE = "PRODUCT_TOTAL_PRICE"
    const val PRODUCT_REDEEMABLE_AGAINST_CREDIT = "PRODUCT_REDEEMABLE_AGAINST_CREDIT"
    const val PRODUCT = "PRODUCT"
    const val PRODUCT_URL = "PRODUCT_URL"
    //coupon database
    const val COUPON_UPDATE = "COUPON_UPDATE"
    const val COUPON_ID = "COUPON_ID"
    const val COUPON_CODE = "COUPON_CODE"
    const val COUPON_DISCOUNT = "COUPON_DISCOUNT"
    const val COUPON_DISCOUNT_TYPE = "COUPON_DISCOUNT_TYPE"
    const val COUPON_EXPIRY_DATE = "COUPON_EXPIRY_DATE"
    const val COUPON_ITEM_IDS = "COUPON_ITEM_IDS"
    const val COUPON_ITEM_TYPE = "COUPON_ITEM_TYPE"
    const val COUPON_NAME = "COUPON_NAME"
    const val COUPON_START_DATE = "COUPON_START_DATE"
    const val COUPON_STATUS = "COUPON_STATUS"
    const val COUPON = "COUPON"

    //cart details
    const val SHIPPING_COUNTRY_CODE = "SHIPPING_COUNTRY_CODE"
    const val SHIPPING_POSTAL_CODE = "SHIPPING_POSTAL_CODE"
    const val SHIPPING_TYPE = "SHIPPING_TYPE"
    const val CREDIT = "CREDIT"

    //afterpay orders
    const val AMOUNT = "AMOUNT"
    const val CURRENCY = "CURRENCY"
    //    const val PHONE_NUMBER = "PHONE_NUMBER"
    const val GIVEN_NAMES = "GIVEN_NAMES"
    const val SURNAME = "SURNAME"
    //    const val EMAIL = "EMAIL"
    const val REDIRECT_CONFIRM_URL = "REDIRECT_CONFIRM_URL"
    const val REDIRECT_CANCEL_URL = "REDIRECT_CANCEL_URL"

    //afterpay capture
    const val TOKEN = "TOKEN"
    const val MERCHANT_REFERENCE = "MERCHANT_REFERENCE"

    const val LOGOUT_TOKEN = "token"

    //create oeder
//    const val EMAIL = "EMAIL"
    const val PURCHASE_FIRST_NAME = "PURCHASE_FIRST_NAME"
    const val PURCHASE_LAST_NAME = "PURCHASE_LAST_NAME"
    const val SHIPPING_FIRST_NAME = "SHIPPING_FIRST_NAME"
    const val SHIPPING_LAST_NAME = "SHIPPING_LAST_NAME"
    const val SHIPPING_ADDRESS_LINE_1 = "SHIPPING_ADDRESS_LINE_1"
    const val SHIPPING_ADDRESS_LINE_2 = "SHIPPING_ADDRESS_LINE_2"
    //    const val SHIPPING_COUNTRY_CODE = "SHIPPING_COUNTRY_CODE"
    const val SHIPPING_STATE = "SHIPPING_STATE"
    const val SHIPPING_CITY = "SHIPPING_CITY"
    const val SHIPPING_PHONE = "SHIPPING_PHONE"
    //    const val SHIPPING_POSTAL_CODE = "SHIPPING_POSTAL_CODE"
//    const val SHIPPING_TYPE = "SHIPPING_TYPE"
//    const val PRODUCTS = "PRODUCTS"
//    const val DELIVERY_DATE = "DELIVERY_DATE"
//    const val CREDIT = "CREDIT"
    const val SUB_TOTAL_PRICE = "SUB_TOTAL_PRICE"
    const val TOTAL_DISCOUNT = "TOTAL_DISCOUNT"
    const val CREDIT_DISCOUNT = "CREDIT_DISCOUNT"
    const val SHIPPING_PRICE = "SHIPPING_PRICE"
    const val TOTAL_CART_PRICE = "TOTAL_CART_PRICE"
    const val instructions_notes = "instructions_notes"
    const val IS_CHECKED = "is_checked"
    const val ADMIN_FEE = "ADMIN_FEE"
    const val FREE_PRODUCTS = "FREE_PRODUCTS"
//    const val COUPON_CODE = "COUPON_CODE"
    //update cart
    const val ORDER_ID = "ORDER_ID"
    const val PAYMENT_METHOD = "PAYMENT_METHOD"
    const val PAYMENT_DETAILS = "PAYMENT_DETAILS"
    const val PAYMENT_TRANSACTION_COMPLETED = "PAYMENT_TRANSACTION_COMPLETED"
    const val POSITION = "POSITION"
    const val InvoiceId = "InvoiceId"
    //lawntips detail
    const val LAWNTIPS_ID = "LAWNTIPS_ID"
    //ManageLawn detail
    const val MANAGE_LAWN_ID = "MANAGE_LAWN_ID"
    //search
    const val LAST_SEARCH_KEY = "LAST_SEARCH_KEY"
    const val latitude = "latitude"
    const val longitude = "longitude"
}